[book]
authors = ["Dmytro Katyukha"]
language = "en"
src = "src"
title = "Odood - master Odoo magic with ease."

[output.html]
git-repository-url = "https://github.com/katyukha/Odood"
additional-js = ["mermaid-init.js"]
