{% import odood.lib: _version, is_dev_version %}
{% import odood.lib.assembly.spec %}
FROM ghcr.io/katyukha/odood/odoo/{{ assembly.serie }}:{% if is_dev_version %}latest{% else %}{{ _version }}{% endif %}

{% if assembly.spec.layout == AssemblyLayout.STANDARD %}
COPY {{ assembly.dist_dir }} /opt/odoo/custom_addons/
{% elif assembly.spec.layout == AssemblyLayout.FLAT %}
# WARNING: Building docker images on assemblies with FLAT layout type is not recommended.
#          Please, switch to standard layout, is you need to build docker images.
{% for addon; assembly.spec.addons %}
COPY {{ addon.name }} /opt/odoo/custom_addons/{{ addon.name }}
{% endfor %}
{% else %}
# Layout {{ assembly.spec.layout }} not supported for in docker yet
{% endif %}

{% if handle_requirements_txt %}
COPY "requirements.txt" /tmp/odood-assembly-requirements.txt
RUN odood addons link /opt/odoo/custom_addons && \
    odood venv install-py-packages -r /tmp/odood-assembly-requirements.txt && \
    odood venv python -- -m compileall -q /opt/odoo/custom_addons/ && \
    rm /tmp/odood-assembly-requirements.txt && \
    rm -rf /root/.cache/pip/
{% else %}
RUN odood addons link /opt/odoo/custom_addons && \
    odood venv python -- -m compileall -q /opt/odoo/custom_addons/
{% endif %}

LABEL odoo.serie="{{ assembly.serie }}"
{% if assembly_version %}
LABEL org.opencontainers.image.version="{{ assembly_version }}"
{% endif %}
{% if assembly_source_url %}
LABEL org.opencontainers.image.source="{{ assembly_source_url }}"
{% endif %}
STOPSIGNAL SIGINT

# HEALTHCHECK is inherited from the base Odood image.
# It runs `odood server healthcheck` on a 30s interval with a 120s start period.
# Override it here if the assembly requires different timing.

# ---- ODOOD END DYNAMIC DOCKER CONFIG ----
