name: Release
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
      - 'v*.*.*\+*'

env:
  ODOOD_DLANG_COMPILER: ldc-1.40.1

jobs:
  build-ubuntu:
    name: Build Ubuntu
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Check arch
        id: check-arch
        run: |
          echo "arch=$(dpkg --print-architecture)" >> $GITHUB_OUTPUT

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.ODOOD_DLANG_COMPILER }}

      - name: Install system dependencies
        uses: lyricwulf/abc@v1
        with:
          linux: libzip-dev libpq-dev python3-dev

      - name: Set version from tag
        run: echo "${{ github.ref_name }}" > ./subpackages/lib/data/ODOOD_VERSION

      - name: Check RC/alpha Release
        id: check-rc-release
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-([0-9a-zA-Z.+-]+)$ ]]; then
              echo "is_rc_release=true" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(\+.*)?$ ]]; then
              echo "is_rc_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Odood (Release)
        if: steps.check-rc-release.outputs.is_rc_release == 'false'
        run: |
          dub build -b release -c bash-autocomplete
          dub build -b release

      # We build pre-releases with debug info available.
      - name: Build Odood (Pre-release)
        if: steps.check-rc-release.outputs.is_rc_release == 'true'
        run: |
          dub build -b release-debug -c bash-autocomplete
          dub build -b release-debug

      - name: Install nFPM
        run: |
          wget "https://github.com/goreleaser/nfpm/releases/download/v2.42.0/nfpm_2.42.0_${{ steps.check-arch.outputs.arch }}.deb" -O /tmp/nfpm.deb
          sudo dpkg -i /tmp/nfpm.deb

      - name: Build debian package
        env:
          BUILD_ODOOD_VERSION: ${{ github.ref_name }}
          BUILD_ODOOD_ARCH: ${{ steps.check-arch.outputs.arch }}
        run: nfpm package -p deb -t build/odood_${{ github.ref_name }}_${{ steps.check-arch.outputs.arch }}.deb

      - name: Upload Odood compiled assets
        uses: actions/upload-artifact@v4
        with:
          name: odood-${{ steps.check-arch.outputs.arch }}
          path: |
            build/odood_${{ github.ref_name }}_${{ steps.check-arch.outputs.arch }}.deb

  publish_release:
    name: Publish Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - build-ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: 'Download artifacts for amd64'
        uses: actions/download-artifact@v4
        with:
          name: odood-amd64
          path: build-amd64

      - name: 'Download artifacts for arm64'
        uses: actions/download-artifact@v4
        with:
          name: odood-arm64
          path: build-arm64

      - name: "Prepare release notes"
        run: csplit --prefix=CHANGELOG. --suffix=%02d.md CHANGELOG.md '/---/'

      - name: Check RC/alpha Release
        id: check-rc-release
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-([0-9a-zA-Z.+-]+)$ ]]; then
              echo "is_rc_release=true" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(\+.*)?$ ]]; then
              echo "is_rc_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Release (RC)
        uses: softprops/action-gh-release@v1
        if: steps.check-rc-release.outputs.is_rc_release == 'true'
        with:
          files: |
            build-arm64/odood_${{ github.ref_name }}_arm64.deb
            build-amd64/odood_${{ github.ref_name }}_amd64.deb
          prerelease: true
          body_path: CHANGELOG.00.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.check-rc-release.outputs.is_rc_release == 'false'
        with:
          files: |
            build-arm64/odood_${{ github.ref_name }}_arm64.deb
            build-amd64/odood_${{ github.ref_name }}_amd64.deb
          prerelease: false
          body_path: CHANGELOG.00.md
