name: Tests
on:
  push:
    branches:
      - '*'

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        dc: [dmd-2.104.2, ldc-1.34.0]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install system dependencies
        uses: lyricwulf/abc@v1
        with:
          linux: libzip-dev libpq-dev python3-dev

      - name: Run tests
        run: dub test -b unittest-cov

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          name: odood-unittests
