name: Tests
on:
  push:
    branches:
      - '*'

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        dc: [dmd-2.110.0, dmd-latest, ldc-1.40.1, ldc-latest]
        include:
          - os: ubuntu-22.04-arm
            dc: ldc-1.40.1
          - os: ubuntu-24.04-arm
            dc: ldc-1.40.1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install system dependencies
        uses: lyricwulf/abc@v1
        with:
          linux: libzip-dev libpq-dev python3-dev

      - name: Configure git user (to make git tests work)
        run: |
          git config --global user.email "odood@odood.dev"
          git config --global user.name "Odood"

      - name: Run tests
        run: dub test -b unittest-cov

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          name: odood-unittests
